name = "Vanilla Server 1 21 X"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ecbebdcf32c24b826a21f6b5b228fc69678c885ee792076ab0b3b101fff17ed"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
