name = "Vanilla Server 1 21 X"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07a66a42e55da6cdcc12d3159e410d16f41ce8a4c2980777c3c2dbdd0cea930d"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
