name = "DAM"
author = "Danny Le"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1584dcb6044790b602892a29d1cab82d0f4a05494851f3876d4b5df4a7e17721"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
datapack-folder = "global_packs/required_data"
