noItemSplatterOnDeath = true
noDeathItemDespawn = true
tryItemLavaSaveOnDeath = true
tryItemVoidSaveOnDeath = true
explosionResistantItems = true
playerDropMoreXpOnDeath = false
# Default: 80
# Range: 1 ~ 100
droppedExperiencePercent = 50
keepArmorOnDeath = false
keepHotbarOnDeath = false
