name = "Vanilla Server"
author = "Danny Le"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0b6ca965b28dcf58f3965b29bbd8455f28f865c798944fa7e9ca765a76bb83b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
