name = "Sunlit Valey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad4efe96f86ecf70c3d1e3f65ad4b5af08c56a2d4dd49cbe68a9a2f7ab677b75"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
