name = "Sunlit Valey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "946a7a5c380cdf80990dbdda70397c9251afc00c83f2fbde595baca1d3f80787"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
