name = "Sunlit Valey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b08c4ee8d4a246301417f33f8f8b25ab1d1cfaee6a91a0485d448c9b8858fa8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
