name = "COBBLEVERSE"
author = "LUMYVERSE"
version = "1.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b67335fe05fab76815925dfc16005b042d51ad6a5ba87ebc74f50016b72f08a6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
