name = "Cobbleverse"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acf6c52f839e4795541aaaad4e4e3ae0f126f491175753cb75f029f543e36d1e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
