name = "COBBLEVERSE"
author = "LUMYVERSE"
version = "1.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "494b6dbc96457158453af3f6bf49420ec0ea075ca89fc2101220d24dfed6ec49"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
