name = "Creative Latest"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3373ebe31e74dce8dfccb0728f0f6f08df80a8c7637f81bbf452d4f8fd662014"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
