name = "DAM (1.20.1)"
author = "Danny Le"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "961d7b0674f1e7410862debfb60d8a84b76e3f8b004c55e67bd1797472485ba6"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
