name = "DAM (1.20.1)"
author = "Danny Le"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "510d49d651f6ceda07d77f1977ca4a6b0bafef922e92bd53a17546ed2c6c2a98"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
