name = "DAM (1.20.1)"
author = "Danny Le"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae53b7aff7a4dfd83716714d33f8eba0161e3c22d120e959a409da93d0f20272"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
