name = "DAM (1.20.1)"
author = "Danny Le"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12861f6f285008ac78dc58be4253f3d94915e244f7020132b742ac335acf8a6f"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
