name = "DAM (1.20.1)"
author = "Danny Le"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70db4b5f91b47279ba850bcd31c1519323abd9849435759b99d09b5f2791b2b7"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
