name = "DAM (1.20.1)"
author = "Danny Le"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf7d39bd759c242eabbacfbf45c1de00fed7a3540944401d8fd7a49f2cf381c9"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
